"""
An authentication function set.
"""
from django.conf import settings
from django.contrib.auth import authenticate, get_user_model
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode

from rest_framework import serializers

from .models import Profile
from .tokens import account_activation_token


def update_social_name(backend, user, response, *args, **kwargs):
    """
    Used to set social name after social account login.
    Called from .settings.SOCIAL_AUTH_PIPELINE

    Args:
        user(:obj: get_user_model) : The login user object.
    """
    del backend, response, args

    if not user:
        return
    profile, _ = Profile.objects.get_or_create(user_id=user.id)
    if not profile.social_name:
        profile.social_name = kwargs.get('details').get('fullname')
        profile.save()


def update_name(user, social_name):
    if not user:
        return None
    Profile.objects.update_or_create(
        user_id=user.id,
        defaults={'social_name': social_name},
    )
    # profile.social_name = social_name
    # profile.save()
    return user


def create_user_account(email, password):
    """
    Used to create account with email.
    """
    user = get_user_model().objects.create_user(email=email, password=password)
    user.backend = 'django.contrib.auth.backends.ModelBackend'
    user.email_confirmed = False
    user.is_social_auth = False
    user.save()
    return user


def get_and_authenticate_user(email, password):
    """
    Used to authenticate the user.
    """
    user = authenticate(username=email, password=password)
    if user is None:
        raise serializers.ValidationError(
            'Invalid username/password. Please try again!')
    return user


def send_verification_email(user):
    """
    Used to send email with verification information.
    """
    current_site = f'{settings.FRONTEND_URL}:{settings.FRONTEND_PORT}'
    subject = 'Activate Your Account'
    message = render_to_string(
        'email/account_activation.html', {
            'user': user,
            'domain': current_site,
            'uid': urlsafe_base64_encode(force_bytes(user.pk)),
            'token': account_activation_token.make_token(user),
        })
    user.email_user(subject, message)


def activate_account(uidb64, token):
    """
    Activate account from email.

    Args:
        uidb64: The encoded value by user.pk
        token: A verified token generated by account_activation_token.

    Retruns:
        A tuple items forms by success and user.
        Index 0: True if activate successful.
        Index 1: User object if activate successful, otherwise None.
    """
    try:
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = get_user_model().objects.get(pk=uid)
    except (TypeError, ValueError, OverflowError,
            get_user_model().DoesNotExist):
        return (False, None)

    if user is not None and account_activation_token.check_token(user, token):
        user.backend = 'django.contrib.auth.backends.ModelBackend'
        user.email_confirmed = True
        user.save()
        return (True, user)

    return (False, None)
